### ISSUE TITLE
AWS CLI

### ISSUE THREAD

**Issue by brianabston001** [vegardit/cygwin-portable-installer#10]
This looks like something we have been needing.. Is there a way to also add AWS CLI to this?

**Comment by sebthom** [comment]
Good idea. Thanks!

**Comment by brianabston001** [comment]
Maybe I am doing something wrong.. When the command window comes up I am still not able to run AWS CLI.. Says -bash: aws: command not found

**Comment by sebthom** [comment]
@brianabston001 can you execute /usr/local/bin/aws?

**Comment by brianabston001** [comment]
Not sure what was going on.. but it is working now.  Is it supposed to run `Installing [AWS CLI]...` everytime it is launched?

**Comment by evandrocoan** [comment]
Why enable it by default?

I was wondering why my installation was taking longer and I found this was recently added.
