### ISSUE TITLE
Potential conflict in setup.

### ISSUE THREAD

**Issue by userdocs** [vegardit/cygwin-portable-installer#12]
I was not sure so i thought i'd ask first about these two lines.

https://github.com/vegardit/cygwin-portable-installer/blob/master/cygwin-portable-installer.cmd#L284-L285

If i am reading this right you want to set a custom path for the packages cache. Then use sed to edit the default line. The problem i see is that it matches nothing as the format of the line is :

~~~
last-cache
	C:\...\...\...\.pkg-cache
mirrors-lst
~~~

This works for me actually edit the line as it is created by the Cygwin installer.

~~~
pkg_cache_dir=$(cygpath -w "$CYGWIN_ROOT/../cygwin-pkg-cache")
sed -ri 's#(.*)\.pkg-cache$#'"\t${pkg_cache_dir//\\/\\\\}"'#' /etc/setup/setup.rc
~~~ 

Edit: what it makes me think though is if this is even necessary to do as I dont really see the purpose it serves.

**Comment by sebthom** [comment]
Goot catch, thanks!
