### ISSUE TITLE
download of setup-x86.exe / setup-x86_64.exe fail  (downloader.vbs(7, 1) WinHttp.WinHttpRequest: An error occurred in the secure channel support)

### ISSUE THREAD

**Issue by bofhbug** [vegardit/cygwin-portable-installer#13]
###########################################################
# Installing [Cygwin Portable]...
###########################################################

Creating Cygwin root [U:\cygwin-portable-new-test\cygwin]...
Creating [U:\cygwin-portable-new-test\downloader.vbs] script...
Downloading 'https://cygwin.org/setup-x86_64.exe' to 'U:\cygwin-portable-new-test\cygwin\setup-x86_64.exe'...
U:\cygwin-portable-new-test\downloader.vbs(7, 1) WinHttp.WinHttpRequest: An error occurred in the secure channel support

Running Cygwin setup...
'"U:\cygwin-portable-new-test\cygwin\setup-x86_64.exe"' is not recognized as an internal or external command,
operable program or batch file.

###########################################################
# Installing [Cygwin Portable] FAILED!
###########################################################

**Comment by bofhbug** [comment]
im working on a solution,

**Comment by sebthom** [comment]
Maybe something like this helps in your case: https://stackoverflow.com/questions/21354992/an-error-occurred-in-the-secure-channel-support-classic-asp-http-request/52193257#52193257

**Comment by bofhbug** [comment]
I tried it, on the win 7 boxes I have access to, it won't work

**Comment by sebthom** [comment]
I unfortunately cannot reproduce that issue. The download works fine for me on Windows 7 and Windows 10.

**Comment by p1nkhat** [comment]
same problem here, win10 and 7.
Any solution?

**Comment by userdocs** [comment]
Can you try this?

Change this line
 https://github.com/vegardit/cygwin-portable-installer/blob/master/cygwin-portable-installer.cmd#L136

To this, and see if it works for you.

~~~
echo Set req = CreateObject("MSXML2.XMLHTTP.6.0"^)
~~~

**Comment by sebthom** [comment]
@bofhbug could you solve the issue for your environment?

**Comment by bofhbug** [comment]
@sebthom yes with 
echo Set req = CreateObject("MSXML2.XMLHTTP.6.0"^)
it works most times, like in 80% 
(i think i is depending on the CDN)

we shud add a check with Sigcheck and gpg to catch also this problems.
