### ISSUE TITLE
Personalize installer

### ISSUE THREAD

**Issue by buxx** [vegardit/cygwin-portable-installer#14]
Hello,

Thank's for your greatfull project ! Just a simple question: if i want to personalize this installer (to adapt to my own application requirements) remove all no necessary and add required things in `https://github.com/vegardit/cygwin-portable-installer/blob/master/cygwin-portable-installer.cmd` is there the correct way ? Or there are variables to personalize ?

**Comment by sebthom** [comment]
Hi Bastien, 


at the moment the way to customize is by modifying the script directly. i. e. the variables between **CONFIG CUSTOMIZATION START** and **CONFIG CUSTOMIZATION END**. We could maybe change the file so that custom settings are loaded from  separate file.
