### ISSUE TITLE
Installing on shared folder makes apt-cyg unavailable

### ISSUE THREAD

**Issue by lmachucab** [vegardit/cygwin-portable-installer#21]
For context: I main Linux systems and only run Windows via a number of VMs - development, work, etc. In order to save space and synchronize featuresets, my intention was to install a single instance of cygwin‑portable on a shared folder in the real host and then run the instance by mapping the networked drive on the Windows VMs.

The configuration for the shared folder is as follows:

````
[winshared]
browseable = yes
force user = winshared
force group = sharing
force create mode = 0777
force directory mode = 0775
acl allow execute always = True

````

Cygwin-Portable itself installs correctly. The problem is that the post-setup scripts in charge of installing apt-cyg, which I think run upon first opening conemu? download and install apt-cyg with some sort of permission issue that makes it unavailable:

```
root@Usuario-PC ~
$ ls /usr/local/bin
drwxrwxr-x  1 Unknown+User Unix_Group+1885   0 abr 13 12:44 .
drwxrwxr-x  1 Unknown+User Unix_Group+1885   0 abr 13 12:34 ..
-rw-rw-r--+ 1 Unknown+User Unix_Group+1885 65K abr 13 12:48 apt-cyg

root@Usuario-PC ~
$ apt-cyg
bash: /usr/local/bin/apt-cyg: Permission denied
````

Attempting to ``chmod +x`` the file has no observable effect:

````
root@Usuario-PC ~
$ chmod ugo+x /usr/local/bin/apt-cyg

root@Usuario-PC ~
$ ls -lha /usr/local/bin/
total 1,0M
drwxrwxr-x  1 Unknown+User Unix_Group+1885   0 abr 13 13:04 .
drwxrwxr-x  1 Unknown+User Unix_Group+1885   0 abr 13 12:34 ..
-rw-rw-r--+ 1 Unknown+User Unix_Group+1885 65K abr 13 12:48 apt-cyg

````

getfacl reports available permissions:

````
root@Usuario-PC /usr/local/bin
$ getfacl apt-cyg
# file: apt-cyg
# owner: Unknown+User
# group: Unix_Group+1885
user::rw-
user:Unknown+User:rw-
group::r--
group:Unix_Group+1885:r--
mask::rw-
other::r--
````

But using setfacl to try and modify them also has no observable effect.

The only apparent way to make the apt-cyg binary available is to raw-copying to a new filename, but it can't be placed anywhere in ``$PATH``:

````
root@Usuario-PC /usr/local/bin
$ cat < apt-cyg > /usr/bin/apt-cyg2
$ cat < apt-cyg > /usr/local/bin/apt-cyg2
$ cat < apt-cyg > /tmp/apt-cyg2

$ /usr/bin/apt-cyg2
bash: /usr/bin/apt-cyg2: Permission denied
$ /usr/local/bin/apt-cyg2
bash: /usr/local/bin/apt-cyg2: Permission denied
$ /tmp/apt-cyg2
[normal apt-cyg output]
````

I presume this error could affect other components of Cygwin-Portable too, but since apt-cyg is not working correctly I can't install more software to test ATM. The components first installed by the system (ie.: anything listed in installer.cmd the *first* time) work without issue, but I can't tell at the moment about anything installed after.

For the record, installing Cygwin-Portable on the actual hard-drive works as intended, but copying the result to the shared folder results in the same errors as the above. Which defeats the point of having the install being portable.

Host: Linux Debian 10 with Samba
Guests:

* Windows 7 FLP 32-bit
* Windows 7 SP1 32-bit
* Windows 8.1 32-bit

**Comment by sebthom** [comment]
Hi Luis, can you try to install cygwin on the network share directly using the official [setup-x86\_64.exe](https://cygwin.com/setup-x86_64.exe) , then manually install https://github.com/kou1okada/apt-cyg and see if this works?

**Comment by userdocs** [comment]
I had a permissions issue similar to this when moving from one pc to another that there seems to be no fix for( i forgot the reasoning for it ). The only way around this was to install to the user home directory as Cygwin appears to handle these files differently.

So i now install it to `~/bin/apt-cyg` and added this to the `PATH` and this particular problem went away. Try it and see if it helps your issue.

**Comment by lmachucab** [comment]
Both solutions provided work correctly, just tested them yesterday, thanks!

@userdocs This being a permissions issue does make sense. When I use a Samba share from a Linux machine I experience this issue either when installing locally or when copying the install from a different drive, but if I use the shared folder system provided by Virtualbox, only installing locally fails whereas copying the files works correctly. I'm also puzzled that so far this *only* happens to apt-cyg and apparently to any binary you manually copy to ``$PATH``; but the files added by the installer(s) are not affected.

Is there any chance the username you set up in the installer could be related to this? Since it seems to default to "root" but I don't know exactly what that username refers to.

**Comment by userdocs** [comment]
I think would make more sense looking at it from a windows permissions perspective.

I played with usernames, groups and even created the the file [using windows cmd before cygwin was called](https://github.com/userdocs/LFTP4WIN/blob/master/LFTP4WIN-installer.cmd#L152). As soon as you run Cygwin it does something to the acls, to all files outside the home folder, that you cannot mitigate. This was especially obvious when using this portably and not really evident on a single machine. I think your situation emulates the portable scenario.

From what the windows properties file was being set with null values by cygwin acls making the file unreadable to the host machine.

Right click on the file and view the properties/security tab and you will see what i mean.

**Comment by sebthom** [comment]
There are two things we currently do regarding ACLs:
1. During installation `icacls "%CYGWIN_ROOT%" /T /grant "%USERNAME%:(CI)(OI)(F)"` is executed. 
1. In `/etc/fstab` we set
   ```bash
   # noacl = disable Cygwin's - apparently broken - special ACL treatment which prevents apt-cyg and other programs from working
   none /cygdrive cygdrive binary,noacl,posix=0,user 0 0
   ```

So maybe to solve the issue we either should run the icacls command everytime cygwin is started (since it may have been moved/copied around and thus permissions changed) and/or do configure `/etc/fstab` differently.

Maybe you can play around with these things and see if something improves the situation.

**Comment by sebthom** [comment]
@lmachucab did you find a solution for your case?

**Comment by lmachucab** [comment]
Unfortunately I have not been able to retest any often as I'd like due to having to install Cygwin on a VM already being an arduous task. ATM I'm being held back from any sort of installs due to an error that says ``WinHttp.WinHttpRequest: An error occurred in the secure channel support`` which is apparently Issue nro. #13 , but I can't find a reasonable solution to it that I can apply, except for trying to find and use a HTTP mirror, of which I've found nothing as of late.

If there is an official HTTP mirror for Cygwin that I can use, I can continue testing this issue.

It might be my misunderstanding but, apparently because of the APIs used, it's not possible to install cygwin-portable in any Windows environment that is not "Full" (ie.: Professional, fully updated). Because I use VMs to save on resources and ATM my only Wndows >= 7 VM is *Windows Fundamentals for Legacy PCs*, the only "straightforward" way of installing Cygwin that I have ATM is using the old installers that work in Windows XP VMs.

**Edit**: To amend the above, unless HTTP downloads for the basic cygwin portable components are available (cygwin itself, conemu) it is not possible for me to continue testing on Windows 7. I'm trying to get access to a Windows 8 machine for further testing, but it already doesn't correspond to my use case.

**Comment by lmachucab** [comment]
I got myself remote access to a few machines and obtained some possibly revealing results:

Clean install of Windows 7 SP1 (virtualized):

* Impossible to complete initial install due to #13 (incorrect or missing SSL support), not possible to triage the actual apt-cyg issue.
* Copying another install (see below) onto a local hard drive works without issues, with apt-cyg working correctly.
* Copying another install (see below) onto a *network drive* copies incorrectly, some files in ``/usr/bin`` and ``/usr/local/bin`` (including apt-cyg) are copied as 0-bytes and without "Read and Execute" permission.
* Manually copying the install onto a networked drive by going outside the (virtual) machine and using Linux's command line to copy the files (in a physical environment equivalent to using a Live-CD) copies the files correctly, but they still don't inherit the "Read and Execute" permission.
* Even performing the copy to the networked drive as an user with administrative permissions does not inherit the files the required "Read and Execute" permission.

Working install of Windows 7 SP1 (virtualized):

This is the VM environment I usually use. It has a number of regedit and DLL hacks to try and make Issue #13 work, and has a number of runtimes and softwares already installed, so I can't say how much of this is reproducible.

* Installing Cygwin-Portable on a local hard drive functions correctly if "apt-cyg", "ansible", "funk-bash" etc are ALL set to "``NO``" (missing SSL support, apparently). 
* Manually copying the apt-cyg binary causes it to fail with a message like this:

``exec: env: /usr/bin/bash: Not Found``

* The error can be fixed by manually editing the shebang in the ``apt-cyg`` binary. I'm not aware if the normal cygwin-portable installer does this automatically.
* Installing on a *network drive* completes (with all the optionals set to "``NO``"), but cygwin-portable itself can not start correctly, complaining about missing or unreadable files.
* Checking the directory trees reveals that some files in ``/usr/bin`` are created as 0-bytes and no "Read and Execute" permission.
* Copying the entire directory tree manually from another working system makes cygwin-portable (and apt-cyg) work, but the "Read and Execute" permissions have to be given en-masse by hand.

Windows 8.1 clean install + .NET Framework and Security Windows Updates:

* Installing on a local hard drive works without issues, apt-cyg installs without issues.
* ``apt-cyg`` still fails to execute with error about ``env: /usr/bin/bash: Not Found``.
* Manually fixing the she-bang fixes the problem.
* Installing on a *network drive* completes, but upon running cygwin-portable complains about missing or unreadable binaries.
* The files in ``/usr/bin`` are created with correct non-zero sizes, but they lack the  "Read and Execute" permission.
* Manually giving the entire directory tree "Read and Execute" permission (via the Security Dialog on the *folder*) works.
* The resulting install can be, for the most part, copied to other machines so long as 1.- the copy is not done via Windows and 2.- "Read and Execute" permissions are manually re-granted at the destination.

All in all, it seems to be something related to how the concept of "portable" relates (or not) to the concept of "networked" on Windows.

**Comment by freeload101** [comment]
sounds just like a permissions issue ...nothing to do with Cygwin or the script...below may help but depending on the network share perms it may not. Windows ASL's are stupid. Just make sure everybody else running it has the same perms as the user that installed it you traditionally will be fine. 


cd z:
takeown /F "%CD%" /R
icacls "%CD%" /GRANT Users:F /T
cacls "%CD%" /E /T /C /G Users:F
cygwin-portable.cmd
