### ISSUE TITLE
xargs: too low environmental memory

### ISSUE THREAD

**Issue by SuperChecker** [vegardit/cygwin-portable-installer#22]
xargs: Der Umgebungsspeicher ist für »exec« nicht ausreichend.

The active image address is not contained in the flash layout, please check !!!

What can I do?

**Comment by sebthom** [comment]
Hi Andreas,
try to disable loading of bashfunk by commenting out the following line in `~/.bashrc`:
```bash
source /opt/bash-funk/bash-funk.sh
```
