### ISSUE TITLE
npm does not work

### ISSUE THREAD

**Issue by inadavid** [vegardit/cygwin-portable-installer#23]
I had done a standard installation without any change to installer file. the installer later reported a successful installation including node.js
When type `npm` command, i get below error message:

$ npm -v
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\PortableApps\CygwinPortable\cygwin\opt\nodejs\current\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\PortableApps\CygwinPortable\cygwin\opt\nodejs\current\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

the installer bat file is placed in `C:\PortableApps\CygwinPortable\` but above command is executed in cygwin env.
any idea how to fix it? thanks.

**Comment by sebthom** [comment]
Hi David,

try to create an alias like this for now:
```bash
$ alias npm='cmd /c $(cygpath -w $NODEJS_HOME/npm.cmd)'

$ npm
Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
```

**Comment by inadavid** [comment]
> 
> 
> Hi David,
> 
> try to create an alias like this for now:
> 
> ```shell
> $ alias npm='cmd /c $(cygpath -w $NODEJS_HOME/npm.cmd)'
> 
> $ npm
> Usage: npm <command> 
> 
> where <command> is one of:
>     access, adduser, audit, bin, bugs, c, cache, ci, cit,
> ```

Thanks @sebthom , it works. it's just i need to manually add all globally installed libraries to .bashrc file. so far so good.
