### ISSUE TITLE
It is not portable

### ISSUE THREAD

**Issue by KushalSM** [vegardit/cygwin-portable-installer#24]
I installed it but when I run it on a different computer it show account of the users of the computer instead of my user. Please help me??

**Comment by userdocs** [comment]
This is not the solutions fault but a Cygwin issue. You will need to do something like this.

```
@echo off
:: Move to the LFTP4WIN root directory
PUSHD "%~dp0.."
:: If this fails then exit
If %errorlevel% NEQ 0 goto:eof
:: Set the path to a variable.
set FIX_PERMS_PATH="%CD%"
:: Take ownership and reset permissions
takeown /f "%FIX_PERMS_PATH%" /r & icacls "%FIX_PERMS_PATH%" /reset /t /c /q
:: Press enter to exit the script
pause
```

This is what is do https://github.com/userdocs/LFTP4WIN-CORE/blob/master/help/troubleshooting%20-%20ownership.cmd

**Comment by KushalSM** [comment]
Can you give more detail of where to keep it and all

**Comment by userdocs** [comment]
`permissions.bat` inside the portable directory.

Run as admin.

**Comment by sebthom** [comment]
> I installed it but when I run it on a different computer it show account of the users of the computer instead of my user. Please help me??

@KushalSM 
What do you mean with "it shows account of the user of the computer." Where does it show this? What does not work?  Can you provide screenshots of how it looks on the computer you installed it vs. on the different computer you are trying to run it.

**Comment by KushalSM** [comment]
@sebthom 
I have actually uninstalled it, but I can give you the details..

Basically, cygwin portable means that the same user must be used in whatever computer. For example my username is kushs when I first downloaded it, so basically the usernme should be kushs even if I use it any other computer.. Bout that is not the case..

Say the other computer I want to use it in has a username say 193265(which is actually the username of the computer I tried in), when I load it up it does the fstab part, but then it says that is going to create a temporary directory for the user 193265 and brings me to the folder and start the terminal...

But instead shouldn't it not tell what I said above and login to my original account kushs..

That's why I raised the issue that it is not portable..

**Comment by KushalSM** [comment]
@userdocs 
Hi, I have actually uninstalled cygwin so I will have to install it again and try the the edit of the batch file..

If it works I will be informing in this issue and close it..

**Comment by freeload101** [comment]
This is not a cygwin issue .. nor is it an issue with this repo etc .. your best bet is the following:

the issue:
* you run something as a user in NTFS or whatever file system
* you move the files to a different system or mount them etc some place else on another filesystem NTFS etc
* that file system has no idea who SID 123445345243-2345-2345234-2345-2345 is and can't bind a user on that system... and depending on the file/folder permissions you may not have given yourslef any other way to get read/write to the files/folders .
* the administrator ,guest and everyone etc I think all have the same SID ... so you can be safe setting them from system to system... 



Easy fix: Format USB or whatever to fat32 or XFAT so you will never have any permissions issues
Pros: you never need to worry about file permissions really 
Con: XFAT and fat32 have some limitations to the filesystem etc .. and if your disk or devices is NTFS and your boot this wont work ... easily ... ( you could use gparted to squish you NTFS and create a xfat volume to install stuff you want everyone to have access to .. )

Harder Fix: 
* create a folder where your cygwin will live example f:\cygwin 
* then set the permissions to (everyone) before you put ANYTHING in that folder example:
takeown /r /d y /f f:\cygwin 
icacls f:\cygwin  /t  /grant Everyone:F

Pros: 
*this will work across any NTFS file system etc ... 
* you can even "hide" the files from other users on the domain/local users .. if you set ONLY perms to say BOB and NOTHING else any app scanner that's etc trys to read the folder they won't be able to :P I use this to hide files/folders on network shares I don't want people poking with. :P 

Cons: 
* hard to do if you suck at windows file permissions  and/or don't have local admin on the folder with stuff already in it you don't have access to ...
* keep in mind for every file you 'write' as whatever user it WILL break on a different computer that has NTFS etc  if you dont fix them before you move the files over etc ..

**Comment by freeload101** [comment]
This is not a cygwin issue .. nor is it an issue with this repo etc .. your best bet is the following:

Easy fix: Format USB to fat32 or XFAT so you will never have any permissions issues
Pros: you never need to worry about file permissions really 
Con: XFAT and fat32 have some limitations to the filesystem etc .. and if your disk or devices is NTFS and your boot this wont work ... easily ... ( you could use gparted to squish you NTFS and create a xfat volume to install stuff you want everyone to have access to .. )

Harder Fix: 
* create a folder where your cygwin will live example f:\cygwin 
* then set the permissions to (everyone) before you put ANYTHING in that folder example:
takeown /r /d y /f f:\cygwin 
icacls f:\cygwin  /t  /grant Everyone:F

Pros: this will work across any NTFS file system etc ... 
Cons: hard to do if you suck at windows file permissions  and/or don't have local admin on the folder with stuff already in it you don't have access to ...
