### ISSUE TITLE
[Question] Install/Uninstall cygwin package using cygwin setup.exe?

### ISSUE THREAD

**Issue by meav** [vegardit/cygwin-portable-installer#26]
Can I install or uninstall one cygwin package using cygwin setup.exe? Have a batch file like `cygwin-portable-installer.cmd`, `cygwin-portable-updater.cmd` to install more cygwin package?
Or the only way to install more package is using cyg-apt?
Sorry for my bad english and thanks for reading!

**Comment by meav** [comment]
I can add cygwin packpage into `cygwin-portable-installer.cmd` to install more cygwin packpage.
But remove cygwin packpage from `cygwin-portable-installer.cmd` not uninstall package.

**Comment by sebthom** [comment]
You are right, if you re-run the installer and remove packages from the CYGWIN_PACKAGES environment variable, they will not be un-installed. You will have to manually remove them using cyg-apt.
