### ISSUE TITLE
Find Command Issues

### ISSUE THREAD

**Issue by freeload101** [vegardit/cygwin-portable-installer#28]
Don't have this issue with my old Cygwin env same binary for find too. Can't seem to find a fix with the conemu :(  :

![image](https://user-images.githubusercontent.com/4307863/100133315-98c35200-2e54-11eb-90e6-9f03a0e0fec4.png)

If I just run bash.exe from CMD it works fine:

`bash -c "/bin/find . -exec /bin/ls '{}' \;`

**Comment by sebthom** [comment]
Please try to update bashfunk using the command `-update --reload` and try again.

**Comment by freeload101** [comment]
Thanks! Worked great!

`$ -update -yr ; find . -maxdepth 1 -exec ls '{}' \;
HEAD is now at d277bd2 add google verification
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
Sourcing [~/.bash_funk_rc]...
 _               _            __             _
| |__   __ _ ___| |__        / _|_   _ _ __ | | __
| '_ \ / _` / __| '_ \  ____| |_| | | | '_ \| |/ /
| |_) | (_| \__ \ | | |/___/|  _| |_| | | | |   <
|_.__/ \__,_|___/_| |_|     |_|  \__,_|_| |_|_|\_\
                     github.com/vegardit/bash-funk

Local Version: 2020-11-21 15:50:09 +0100

* Loading [modules/aws.sh]... SKIPPED
* Loading [modules/docker.sh]... SKIPPED
* Finished loading applicable modules.
* Exporting functions...
* Executing command '-tweak-bash'...
* Setting custom bash prompt...
* Loading directory history...

You are ready to go. Enjoy!
1  1.txt  pypykatz
./.bashrc
./.bash_funk_dirs
./.bash_funk_history
./.bash_funk_rc
./.bash_profile
pip
./.inputrc
./.profile
./.python_history
./.viminfo
./.wget-hsts
./1
./1.txt
LICENSE  MANIFEST.in  Makefile  README.md  build  dist  pypykatz  pypykatz.egg-info  setup.py

root@NATL1-8K8L7H2 | 10:12:28 | 0 jobs | tty #pty0
[~]`
