### ISSUE TITLE
"An error occurred in the secure channel support" when attempting to download cygwin installer

### ISSUE THREAD

**Issue by dizzy-egg** [vegardit/cygwin-portable-installer#31]
Please be aware that users may be unable to download the cygwin installer via the vbscript method if their system doesn't support TLS 1.1/1.2 in WinHTTP connections.

They'll see an error when running the installer: `"An error occurred in the secure channel support"`.

The solution is to make the registry changes or apply the hotfix [detailed here](https://stackoverflow.com/a/52841060/1652951).

Please add this to the README or perhaps consider a workaround - such as allowing users to manually download and place thee cygwin installer executable in the required subfolder - if possible.

**Comment by sebthom** [comment]
Thanks for the info. Which OS are you using? Did the installer also fail using powershell to download the cygwin setup exe? Powershell is configured as a fallback in case vbscript does not work.

**Comment by no-e-in** [comment]
In win7, with both cmd and powershell, I encountered the error shown by dizzy-egg. I solved it with the microsoft [fix ]( https://aka.ms/easyfix51044) mentioned in the stackoverflow article cited by dizzy-egg.
