### ISSUE TITLE
Postinstallation error in ca-certificates.sh

### ISSUE THREAD

**Issue by barcala** [vegardit/cygwin-portable-installer#36]
When running the script with its defaults, an error message is shown on the screen and continues. I don't know exactly the consequences of the problem:

```
...
running: C:\cygwin\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/p11-kit.sh"
running: C:\cygwin\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/ca-certificates.sh"
abnormal exit: exit code=1
running: C:\cygwin\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/crypto-policies.sh"
...
```

**Comment by sebthom** [comment]
I haven't seen this one before. the postinstall scripts are part of cygwin itself. would be interesting to see if you get the same error installing cygwin manually with the installer from theirs website.
