### ISSUE TITLE
Bug - Escape Special Character "!"

### ISSUE THREAD

**Issue by tuxado** [vegardit/cygwin-portable-installer#37]
Some characters in cygwin-portable-installer.cmd need to be escaped before output lines to generated cmd files

example at portable-init.sh:
echo if [[ ! -e /opt/ansible ]]; then  BAD RESULT >> if [[ -e /opt/ansible ]]
should be
echo if [[ ^! -e /opt/ansible ]]; then CORRECT RESULT >> if [[ ! -e /opt/ansible ]]

**Comment by sebthom** [comment]
I cannot reproduce this. `!` does not need to be escaped in windows batch files. and looking at the generated file `cygwin/portable-init.sh` the exclamation mark is still present as expected:
```sh
if [[ ! -e /opt/ansible ]]; then
  echo "*******************************************************************************"
  echo "* Installing [Ansible - stable-2.12]..."
  echo "*******************************************************************************"
  [[ -e /opt ]] || mkdir /opt
  git clone https://github.com/ansible/ansible --branch stable-2.12 --single-branch --depth 1 --shallow-submodules /opt/ansible
fi

```
