### ISSUE TITLE
package manager change

### ISSUE THREAD

**Issue by AireagoirSteam** [vegardit/cygwin-portable-installer#4]
apt-cyg is dead and the authour reccomends the installer called sage.
https://github.com/svnpenn/sage
 i'm not sure how the change would work but the cygwin folder would need to be writable and not read ol since windows sets folders to be this and sage doesn't like it.

Or you could alter the script to download and use setup.exe

**Comment by sebthom** [comment]
The portable installer does not use apt-cyg itself. The apt-cyg installation is an optional convenience feature. You can also install new packages by adjusting the CYGWIN_PACKAGES variable in the installer  batch and rerun it.
