### ISSUE TITLE
bash: /opt/bash-funk/bash-funk.sh: No such file or directory

### ISSUE THREAD

**Issue by no-e-in** [vegardit/cygwin-portable-installer#40]
After:

- installing cygwin (successfully) with cygwin-portable-installer.cmd in win11
- click on cygwin-portable.cmd

I get the error reported in the title. 
Installing bash-funk manually all ok.

**Comment by sebthom** [comment]
Thanks for reporting! Should be fixed now by 516e578edaec2fcc65cb1e8328851d8497ef20ec

**Comment by no-e-in** [comment]
OK
